create table train
(
    serial          varchar(255) not null,
    carriage_number INTEGER      not null,
    capacity        INTEGER      not null,
    constraint train_pk
        primary key (serial)
);
create table station
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    constraint station_pk
        primary key (id)
);
create table trip
(
    id                   BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    departure_time       TIMESTAMP    NOT NULL,
    arrival_time         TIMESTAMP    NOT NULL,
    departure_station_id BIGINT       NOT NULL,
    arrival_station_id   BIGINT       NOT NULL,
    train_serial         VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (departure_station_id) REFERENCES station (id),
    FOREIGN KEY (arrival_station_id) REFERENCES station (id),
    FOREIGN KEY (train_serial) REFERENCES train (serial)
);
